spring.application.name=SpringSecurityDBConnection

spring.datasource.url= jdbc:postgresql://localhost:5432/springsecuritydb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always